### PR TITLE
Solve Undefined index: H at Sync.php#209

### PR DESCRIPTION
**Pull request by rodrigoaguilera**

### CODE REVIEW

**Comment by mrubinsk** [comment]
1) This logic doesn't look correct to me. It reverses the original results of the original comparison. I.e., if you have a highestmodseq, and it's not equal to the current sync data's highestmodseq this will now return false, when it should be true.

2) Do you have any data as to why this is necessary? A stack trace? A properly working and configured imap server should not be missing the 'H' value when the $this->highestmodseq value is set.

**Comment by rodrigoaguilera** [comment]
Thank you for noticing the logic error. I think I got it right this time.

My IMAP server is provided by ZOHO.
I tried to search for complains about ZOHO's IMAP implementation but I only found this
https://github.com/dinhviethoa/libetpan/blob/master/src/low-level/imap/mailimap_parser.c#L7504

This undefined variable warning is flooding the logs for the mail app installed in my nextcloud 13 server.

I tried to reproduce it in a local dev server but is difficult to spot so I can't provide more data until I get more knowledge about how the mail app works.

**Comment by mrubinsk** [comment]
Sorry, this still doesn't look right to me.  Why are you negating the first comparison? If both are true, then the result will be false, and the second comparison will never be evaluated, so flags will never be set to true when it need to be.

**Comment by rodrigoaguilera** [comment]
Oh sorry I was taking the assumption that both were boolean variables. I did not take into account that both can be trueish.

I restored the original logic and just add the check that avoids the warning.

Thanks for the review.

**Pull request closed without merging**
